#!/usr/bin/env python3
"""Generate a sample synthetic traffic video for CTAS.

This is NOT real footage — it is generated by the same deterministic demo
renderer the Demo source uses, and any analysis of it will be watermarked
DEMO / SYNTHETIC DATA.

Usage: python scripts/make_sample_video.py [--seconds 20] [--out samples/sample_traffic.mp4]
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "backend"))

import cv2  # noqa: E402

from app.streaming.demo import DemoSource  # noqa: E402


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--seconds", type=int, default=20)
    ap.add_argument("--out", type=str, default=str(ROOT / "samples" / "sample_traffic.mp4"))
    args = ap.parse_args()

    out = Path(args.out)
    out.parent.mkdir(parents=True, exist_ok=True)

    w, h, fps = 1280, 720, 25.0
    src = DemoSource(width=w, height=h, n_vehicles=14)
    src.open()
    n_frames = args.seconds * int(fps)
    writer = cv2.VideoWriter(str(out), cv2.VideoWriter_fourcc(*"mp4v"), fps, (w, h))
    try:
        for _ in range(n_frames):
            ok, frame, _ts = src.read()
            if not ok:
                break
            cv2.putText(frame, "DEMO / SYNTHETIC DATA", (w // 2 - 260, 40),
                        cv2.FONT_HERSHEY_SIMPLEX, 1.2, (40, 40, 220), 3)
            writer.write(frame)
    finally:
        writer.release()
    print(f"wrote {out} ({args.seconds}s @ {fps}fps)")


if __name__ == "__main__":
    main()
